services:
  api:
    build: .
    container_name: mtg_chatbot_api
    ports:
      - "8000:8000"
      - "8501:8000"
    env_file:
      - .env
    volumes:
      # Mount ChromaDB local persistent files to persist database vector state
      - ./.chroma_db:/app/.chroma_db
      # Mount custom generated card mockups folder
      - ./custom_cards:/app/custom_cards
      # Mount src folder to enable hot-reloading in dev
      - ./src:/app/src
    command: ["uv", "run", "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
    restart: unless-stopped


  test:
    build: .
    container_name: mtg_chatbot_test
    env_file:
      - .env
    # We do not mount the host directory to prevent platform-specific virtualenv conflicts
    # Command executes pytest suite
    command: ["uv", "run", "pytest", "tests/"]
